// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoZ3G9M01vNCIzLNNQlUw-BIFczEfBC4',
    appId: '1:59353616163:android:3db715380d9535a19f8696',
    messagingSenderId: '59353616163',
    projectId: 'bloc-photo-lib',
    storageBucket: 'bloc-photo-lib.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlsUQ2QOfmUmGMon0b-f6fgs64l_7Kp0s',
    appId: '1:59353616163:ios:d9ba1fad12bf7c169f8696',
    messagingSenderId: '59353616163',
    projectId: 'bloc-photo-lib',
    storageBucket: 'bloc-photo-lib.appspot.com',
    iosClientId: '59353616163-vhv8msmajpd8938t06788s3bt5pj2vqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingBloc',
  );
}
